
using UnityEngine;
using VRC.SDKBase;
using VRC.SDK3.Components;
using UdonSharp;

public class MirrorCullDistances : UdonSharp.UdonSharpBehaviour 
{
	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float PlayerCullingDistance = 10F;

	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float PickupCullingDistance = 20F;

	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float OtherCullingDistances = 100F;

	private float[] CullDistances;  
	private Camera MirrorCamera;
	private GameObject MirrorCamObject;

	public void OnWillRenderObject() 
	{
		// Find The Camera Generated By The Mirror
		MirrorCamObject = GameObject.Find(string.Format("/{0}{1}", "MirrorCam", gameObject.name));
		MirrorCamera = MirrorCamObject.GetComponent<Camera>();
		// Wait For Valid Mirror Camera 
		if (VRC.SDKBase.Utilities.IsValid(MirrorCamObject)) 
		{
			// Set Float Array to 32 Length, This Is The Number Of Unity Layers
			CullDistances = new float[32];

			// Set All Undefined Layers Distances
			for(int i=0; i<32; i++) { CullDistances[i] = OtherCullingDistances; }

			// Update Player Layers Culling Distances
			CullDistances[9] = PlayerCullingDistance;  // Player
			CullDistances[10] = PlayerCullingDistance; // PlayerLocal
			CullDistances[18] = PlayerCullingDistance; // MirrorReflection

			// Update Pickup Related Layer Culling Distances
			CullDistances[8] = PickupCullingDistance;  // Interactive
			CullDistances[13] = PickupCullingDistance; // Pickup
			CullDistances[14] = PickupCullingDistance; // PickupNoEnvironment

			// Set The Mirrors Culling Distances From The CullDistances Array
			MirrorCamera.layerCullDistances = CullDistances;
			// Set The Mirrors Culling Type To Spherical
			MirrorCamera.layerCullSpherical = true;

			// Update Internal Mirror Camera Name So Mirrors With Identical Names Can Update Properly
			MirrorCamObject.name = "MirrorCamUpdated";
		 
			//Disable This Behaviour Once Completed
			gameObject.GetComponent<MirrorCullDistances>().enabled = false;
		}
	}
}
