
using UnityEngine;
using VRC.SDKBase;
using VRC.SDK3.Components;
using UdonSharp;

public class MirrorCullDistances : UdonSharp.UdonSharpBehaviour 
{
	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float PlayerCullingDistance = 10F;

	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float PickupCullingDistance = 20F;

	[Tooltip("A Value Of 0 Will Disable Culling Behaviour")]
	public float OtherCullingDistances = 100F;

	[Tooltip("Set Individual Layer Culling Distances")]
	public float[] LayerCullDistances;  

	private Camera MirrorCamera;
	private GameObject MirrorCamObject;

	public void OnWillRenderObject() 
	{
		// Find The Camera Generated By The Mirror
		MirrorCamObject = GameObject.Find(string.Format("/{0}{1}", "MirrorCam", gameObject.name));
		// Wait For Valid Mirror Camera 
		if (VRC.SDKBase.Utilities.IsValid(MirrorCamObject)) 
		{
			MirrorCamera = MirrorCamObject.GetComponent<Camera>();

			// Set Float Array to 32 Length If It Isn't Already a 32 Length Array
			if ((LayerCullDistances.Length != 32)) { LayerCullDistances = new float[32]; }

			// Set All Undefined Layers Distances
			for(int i=0; i<32; i++)
				if ((LayerCullDistances[i] == 0F)) { LayerCullDistances[i] = OtherCullingDistances; }

			// Update Player Layers Culling Distances
			if ((PlayerCullingDistance != 0F)) {
			LayerCullDistances[9] = PlayerCullingDistance;  // Player
			LayerCullDistances[10] = PlayerCullingDistance; // PlayerLocal
			LayerCullDistances[18] = PlayerCullingDistance; // MirrorReflection
			}
			// Update Pickup Related Layer Culling Distances
			if ((PickupCullingDistance != 0F)) {
			LayerCullDistances[8] = PickupCullingDistance;  // Interactive
			LayerCullDistances[13] = PickupCullingDistance; // Pickup
			LayerCullDistances[14] = PickupCullingDistance; // PickupNoEnvironment
			}
			// Set The Mirrors Culling Distances From The LayerCullDistances Array
			MirrorCamera.layerCullDistances = LayerCullDistances;
			// Set The Mirrors Culling Type To Spherical
			MirrorCamera.layerCullSpherical = true;

			// Update Internal Mirror Camera Name So Mirrors With Identical Names Can Update Properly
			MirrorCamObject.name = "MirrorCamUpdated";
		 
			//Disable This Behaviour Once Completed
			gameObject.GetComponent<MirrorCullDistances>().enabled = false;
		}
	}
}
